project:
  title: "Positron"
  type: posit-docs

website:
  page-footer:
    left: |
      Copyright &copy; 2022-2024 Posit Software, PBC. All Rights Reserved.
    center: "Positron Public Beta"
    right:
      - text: "License"
        href: licensing.qmd
      - icon: question-circle-fill
        aria-label: 'Link to Posit Support'
        href: "https://support.posit.co/hc/en-us"
      - icon: lightbulb-fill
        aria-label: 'Link to Posit Solutions'
        href: "https://solutions.posit.co/"
      - text: "<img alt='Link to Posit Documentation' src='images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: "https://docs.posit.co/"
      - text: "<img alt='Link to main Posit site' src='images/posit-icon-fullcolor.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"
  navbar: 
    left:
      - text: "Guides"
        href: interpreters.qmd      
      - text: "Help"
        href: troubleshooting.qmd

  sidebar:
    - title: "Guides"
      style: "docked"
      contents:
        - interpreters.qmd
        - keyboard-shortcuts.qmd
        - data-explorer.qmd
        - connections-pane.qmd
        - updating.qmd

    - title: "Help"
      style: "docked"
      contents:
        - feedback.qmd
        - troubleshooting.qmd
        - faqs.qmd                    
  
